apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.deploy.yaml
- k6.configmap.yaml
- k6.deploy.yaml
- app.pvc.yaml

configMapGenerator:
  - name: k6-script
    files:
      - k6.js
