apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-b
resources:
  - app.ns.yaml
  - ../../base

patchesStrategicMerge:
  - k6.configmap.yaml
  - app.deploy.yaml
  - app.pvc.yaml

